import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const Hero = () => {
  return (
    <>
      <div className="">
        <div className="mt-44 sm:mt-96 ">
          <p className={`${rubik.className} text-6xl w-8/12 font-semibold `}>
            <small className="text-[#28C76F]">i</small> Design <span>&</span>{' '}
            Code
          </p>
          <p className=" mt-16 text-xl text-gray-300 ">
            I’m a web3 front-end developer, a UI designer and a Business Dev.
          </p>
        </div>
        {/* <div className="A-section">
          <img src={down} alt="downward" />
        </div> */}
      </div>
    </>
  )
}

export default Hero
